### Create Article

POST http://localhost:8080/articles
Content-Type: application/json

{
  "author": "John Doe",
  "title": "My first article",
  "content": "This is my first article"
}

> {%
    const articleId = response.body.id;
    client.global.set("articleId", articleId)
%}

### Get Articles By Slug

GET http://localhost:8080/articles/my-first-article

### Get Articles

GET http://localhost:8080/articles

### Filter Articles By Status

GET http://localhost:8080/articles/status/DRAFT

### Delete Article

DELETE http://localhost:8080/articles/{{articleId}}

### Get Comments By Article Id

GET http://localhost:8080/articles/{{articleId}}/comments

### Create Comment

POST http://localhost:8080/articles/{{articleId}}/comments
Content-Type: application/json

{
  "author": "Alice",
  "message": "This is my first comment"
}

> {%
    const commentId = response.body.id;
    client.global.set("commentId", commentId)
%}

### Edit Comment

PUT http://localhost:8080/articles/{{articleId}}/comments/{{commentId}}
Content-Type: application/json

{
  "message": "This is my second comment"
}

### Delete Comment

DELETE http://localhost:8080/articles/{{articleId}}/comments/{{commentId}}
